package com.opsera.integrator.sfdc.correlation;

/**
 * Committed test fixtures for correlation identifier validation scenarios.
 *
 * <p>These constants represent each category of inbound correlation identifier that the
 * {@link CorrelationIdFilter} must handle. They are used by unit and integration tests to
 * prove both passing (safe) and failing (unsafe / replaced) states without introducing real
 * NPM artifacts or external dependencies.
 */
public final class CorrelationIdTestFixtures {

    private CorrelationIdTestFixtures() {}

    // ---- VALID fixtures — filter must accept and propagate these unchanged ----

    /** Standard UUID-style identifier generated by a caller. */
    public static final String VALID_UUID = "550e8400-e29b-41d4-a716-446655440000";

    /** Short alphanumeric trace ID with hyphens and dots (common in distributed tracing). */
    public static final String VALID_SHORT = "req-abc123";

    /** Maximum length valid identifier: 64 printable ASCII chars. */
    public static final String VALID_MAX_LENGTH =
            "abcdefghijklmnopqrstuvwxyz-0123456789_ABCDEFGHIJKLMNOPQRSTUVWX";

    /** Single safe character — minimum valid identifier. */
    public static final String VALID_SINGLE_CHAR = "x";

    // ---- INVALID fixtures — filter must replace with a generated UUID ----

    /** Null / absent header value (request sent without the header). */
    public static final String MISSING = null;

    /** Blank string — all whitespace characters. */
    public static final String BLANK = "   ";

    /** Empty string — zero length value. */
    public static final String EMPTY = "";

    /** Oversized identifier — one byte over the 64-character maximum. */
    public static final String OVERSIZED =
            "abcdefghijklmnopqrstuvwxyz-0123456789_ABCDEFGHIJKLMNOPQRSTUVWXY"; // 65 chars

    /** Control character embedded in an otherwise plausible identifier. */
    public static final String CONTROL_CHAR = "req-abc";

    /** Non-ASCII (Unicode) character in the identifier. */
    public static final String NON_ASCII = "req-éabc";

    /** Newline injection attempt — classic log injection vector. */
    public static final String NEWLINE_INJECTION = "req\ninjected-header: evil";

    /** Carriage return injection attempt. */
    public static final String CARRIAGE_RETURN = "req\rinjection";

    /** SQL-style special characters — unsafe in structured log sinks. */
    public static final String SPECIAL_CHARS = "req'; DROP TABLE--";

    /** Space character — rejected by the safe pattern. */
    public static final String CONTAINS_SPACE = "req abc";
}
