package com.opsera.integrator.sfdc.resources.v2.quickdeploy;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Dedicated v2 request DTO for quick deploy submission.
 *
 * <p>All required fields carry {@code @NotBlank} validation. {@code deployRequestId}
 * is required for quick deploy (unlike the general release command request where it
 * is optional). {@code gitTaskId} is an optional fallback used when the caller cannot
 * supply {@code taskId}; adapter resolution always prefers {@code taskId}.
 *
 * <p>toString() omits {@code clientCorrelationId} to prevent caller-identity metadata
 * from appearing in application logs.
 */
@Schema(description = "V2 quick deploy submission request. "
        + "Submit this to POST /api/v2/sfdc/release-jobs/quick-deploy.")
public class QuickDeploySubmissionRequest {

    @Schema(description = "Quick deploy package/build request identifier",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "deploy-req-fixture-001")
    @NotBlank(message = "deployRequestId is required")
    private String deployRequestId;

    @Schema(description = "Opsera customer identifier",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "customer-fixture-001")
    @NotBlank(message = "customerId is required")
    private String customerId;

    @Schema(description = "Salesforce tool configuration identifier",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "sfdc-tool-fixture-001")
    @NotBlank(message = "sfdcToolId is required")
    private String sfdcToolId;

    @Schema(description = "Primary task identifier (max 256 characters)",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "step-qdeploy-fixture-001")
    @NotBlank(message = "taskId is required")
    @Size(max = 256, message = "taskId must not exceed 256 characters")
    private String taskId;

    @Schema(description = "Optional fallback task identifier. Adapter selects taskId over this value.",
            example = "fallback-task-fixture-001")
    private String gitTaskId;

    @Schema(description = "Pipeline identifier for correlation and logging",
            example = "pipeline-fixture-001")
    private String pipelineId;

    @Schema(description = "Step identifier for correlation and logging",
            example = "step-fixture-001")
    private String stepId;

    @Schema(description = "Optional caller-supplied correlation ID (max 64 characters). "
            + "Generated by the service if absent.",
            example = "corr-caller-supplied-001", maxLength = 64)
    @Size(max = 64, message = "clientCorrelationId must not exceed 64 characters")
    private String clientCorrelationId;

    public QuickDeploySubmissionRequest() {}

    public String getDeployRequestId() { return deployRequestId; }
    public void setDeployRequestId(String deployRequestId) { this.deployRequestId = deployRequestId; }

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public String getSfdcToolId() { return sfdcToolId; }
    public void setSfdcToolId(String sfdcToolId) { this.sfdcToolId = sfdcToolId; }

    public String getTaskId() { return taskId; }
    public void setTaskId(String taskId) { this.taskId = taskId; }

    public String getGitTaskId() { return gitTaskId; }
    public void setGitTaskId(String gitTaskId) { this.gitTaskId = gitTaskId; }

    public String getPipelineId() { return pipelineId; }
    public void setPipelineId(String pipelineId) { this.pipelineId = pipelineId; }

    public String getStepId() { return stepId; }
    public void setStepId(String stepId) { this.stepId = stepId; }

    public String getClientCorrelationId() { return clientCorrelationId; }
    public void setClientCorrelationId(String clientCorrelationId) {
        this.clientCorrelationId = clientCorrelationId;
    }

    @Override
    public String toString() {
        return "QuickDeploySubmissionRequest{" +
                "deployRequestId='" + deployRequestId + '\'' +
                ", customerId='" + customerId + '\'' +
                ", sfdcToolId='" + sfdcToolId + '\'' +
                ", taskId='" + taskId + '\'' +
                ", gitTaskId='" + gitTaskId + '\'' +
                ", pipelineId='" + pipelineId + '\'' +
                ", stepId='" + stepId + '\'' +
                '}';
    }
}
