package com.opsera.integrator.sfdc.resources.v2.validate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Dedicated v2 request DTO for validation submission.
 *
 * <p>Required fields: {@code customerId}, {@code sfdcToolId}, {@code taskId},
 * {@code targetOrgId}. Source control context ({@code repositoryId}, {@code branch})
 * and package context ({@code packageId}) are optional but influence prevalidation
 * warning output when absent.
 *
 * <p>toString() omits {@code clientCorrelationId} to prevent caller-identity metadata
 * from appearing in application logs.
 */
@Schema(description = "V2 validation submission request. "
        + "Submit this to POST /api/v2/sfdc/release-jobs/validate.")
public class ValidationSubmissionRequest {

    @Schema(description = "Opsera customer identifier",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "customer-fixture-001")
    @NotBlank(message = "customerId is required")
    private String customerId;

    @Schema(description = "Salesforce tool configuration identifier",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "sfdc-tool-fixture-001")
    @NotBlank(message = "sfdcToolId is required")
    private String sfdcToolId;

    @Schema(description = "Primary task identifier (max 256 characters)",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "step-validate-fixture-001")
    @NotBlank(message = "taskId is required")
    @Size(max = 256, message = "taskId must not exceed 256 characters")
    private String taskId;

    @Schema(description = "Target Salesforce org identifier for validation",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "org-fixture-001")
    @NotBlank(message = "targetOrgId is required")
    private String targetOrgId;

    @Schema(description = "Optional fallback task identifier. Adapter selects taskId over this value.",
            example = "fallback-task-fixture-001")
    private String gitTaskId;

    @Schema(description = "Source control repository identifier. Used for prevalidation context.",
            example = "repo-fixture-001")
    private String repositoryId;

    @Schema(description = "Source control branch. Used for prevalidation context.",
            example = "main")
    private String branch;

    @Schema(description = "Package or component bundle identifier. Used for prevalidation context.",
            example = "package-fixture-001")
    private String packageId;

    @Schema(description = "Validation mode (e.g. PACKAGE, COMPONENT_LIST). Defaults to PACKAGE when absent.",
            example = "PACKAGE")
    private String validationMode;

    @Schema(description = "Pipeline identifier for correlation and logging",
            example = "pipeline-fixture-001")
    private String pipelineId;

    @Schema(description = "Step identifier for correlation and logging",
            example = "step-validate-fixture-001")
    private String stepId;

    @Schema(description = "Optional caller-supplied correlation ID (max 64 characters). "
            + "Generated by the service if absent.",
            example = "corr-caller-001", maxLength = 64)
    @Size(max = 64, message = "clientCorrelationId must not exceed 64 characters")
    private String clientCorrelationId;

    public ValidationSubmissionRequest() {}

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public String getSfdcToolId() { return sfdcToolId; }
    public void setSfdcToolId(String sfdcToolId) { this.sfdcToolId = sfdcToolId; }

    public String getTaskId() { return taskId; }
    public void setTaskId(String taskId) { this.taskId = taskId; }

    public String getTargetOrgId() { return targetOrgId; }
    public void setTargetOrgId(String targetOrgId) { this.targetOrgId = targetOrgId; }

    public String getGitTaskId() { return gitTaskId; }
    public void setGitTaskId(String gitTaskId) { this.gitTaskId = gitTaskId; }

    public String getRepositoryId() { return repositoryId; }
    public void setRepositoryId(String repositoryId) { this.repositoryId = repositoryId; }

    public String getBranch() { return branch; }
    public void setBranch(String branch) { this.branch = branch; }

    public String getPackageId() { return packageId; }
    public void setPackageId(String packageId) { this.packageId = packageId; }

    public String getValidationMode() { return validationMode; }
    public void setValidationMode(String validationMode) { this.validationMode = validationMode; }

    public String getPipelineId() { return pipelineId; }
    public void setPipelineId(String pipelineId) { this.pipelineId = pipelineId; }

    public String getStepId() { return stepId; }
    public void setStepId(String stepId) { this.stepId = stepId; }

    public String getClientCorrelationId() { return clientCorrelationId; }
    public void setClientCorrelationId(String clientCorrelationId) {
        this.clientCorrelationId = clientCorrelationId;
    }

    @Override
    public String toString() {
        return "ValidationSubmissionRequest{" +
                "customerId='" + customerId + '\'' +
                ", sfdcToolId='" + sfdcToolId + '\'' +
                ", taskId='" + taskId + '\'' +
                ", targetOrgId='" + targetOrgId + '\'' +
                ", gitTaskId='" + gitTaskId + '\'' +
                ", repositoryId='" + repositoryId + '\'' +
                ", branch='" + branch + '\'' +
                ", packageId='" + packageId + '\'' +
                ", validationMode='" + validationMode + '\'' +
                ", pipelineId='" + pipelineId + '\'' +
                ", stepId='" + stepId + '\'' +
                '}';
    }
}
