package com.opsera.integrator.sfdc.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.opsera.integrator.sfdc.exceptions.SfdcExceptionHandler;
import com.opsera.integrator.sfdc.fixtures.SyntheticFixtureFactory;
import com.opsera.integrator.sfdc.governance.audit.AuditEventWriter;
import com.opsera.integrator.sfdc.governance.classification.ClassificationPolicyResolver;
import com.opsera.integrator.sfdc.governance.retention.RetentionMetadataService;
import com.opsera.integrator.sfdc.logging.SafeLogEvent;
import com.opsera.integrator.sfdc.logging.SafeStructuredLogger;
import com.opsera.integrator.sfdc.model.DataMigrationRequest;
import com.opsera.integrator.sfdc.model.PostRefreshRequest;
import com.opsera.integrator.sfdc.service.DataDictionaryService;
import com.opsera.integrator.sfdc.service.DataMigrationService;
import com.opsera.integrator.sfdc.service.PostRefreshTaskService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.verify;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Controller boundary tests using masked synthetic fixture data (WO-124, AC-4, AC-6).
 *
 * <p>All request values are generated by {@link SyntheticFixtureFactory} — no production
 * PII, org URLs, tokens, or customer identifiers appear in this file.
 *
 * <p>Each test asserts that {@link SafeLogEvent#getSafeFields()} contains only the
 * allow-listed fields ({@code pipelineId}, {@code stepId}) and does NOT contain
 * raw org URL values or DTO toString fragments.
 */
class MaskedFixtureControllerTest {

    // ── DataMigrationController ────────────────────────────────────────────────

    @Nested
    @WithMockUser
    @WebMvcTest(controllers = DataMigrationController.class)
    @Import(SfdcExceptionHandler.class)
    @DisplayName("DataMigrationController — masked fixture assertions (WO-124)")
    class DataMigrationMaskedFixtureTests {

        @Autowired
        private MockMvc mockMvc;

        @Autowired
        private ObjectMapper objectMapper;

        @MockBean
        private DataMigrationService dataMigrationService;

        @MockBean
        private ClassificationPolicyResolver classificationPolicyResolver;

        @MockBean
        private SafeStructuredLogger safeStructuredLogger;

        @MockBean
        private AuditEventWriter auditEventWriter;

        @MockBean
        private RetentionMetadataService retentionMetadataService;

        @MockBean
        private DataDictionaryService dataDictionaryService;

        @Test
        @DisplayName("POST /datamigration: safe log event contains pipelineId and stepId")
        void migrate_maskedFixture_safeLogContainsPipelineIdAndStepId() throws Exception {
            String pipelineId = SyntheticFixtureFactory.pipelineId("dm-safe-log-01");
            String stepId = SyntheticFixtureFactory.stepId("dm-safe-log-01");
            String sourceOrgUrl = SyntheticFixtureFactory.sourceOrgUrl("dm-safe-log-01");
            String targetOrgUrl = SyntheticFixtureFactory.targetOrgUrl("dm-safe-log-01");

            DataMigrationRequest request = new DataMigrationRequest(
                    pipelineId, stepId, sourceOrgUrl, targetOrgUrl);

            mockMvc.perform(post("/datamigration")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            assertThat(event.getSafeFields()).containsKey("pipelineId");
            assertThat(event.getSafeFields()).containsKey("stepId");
            assertThat(event.getSafeFields().get("pipelineId")).isEqualTo(pipelineId);
            assertThat(event.getSafeFields().get("stepId")).isEqualTo(stepId);
        }

        @Test
        @DisplayName("POST /datamigration: safe log event does NOT contain sourceOrgUrl or targetOrgUrl")
        void migrate_maskedFixture_safeLogExcludesOrgUrls() throws Exception {
            String pipelineId = SyntheticFixtureFactory.pipelineId("dm-url-exclusion-01");
            String stepId = SyntheticFixtureFactory.stepId("dm-url-exclusion-01");
            String sourceOrgUrl = SyntheticFixtureFactory.sourceOrgUrl("dm-url-exclusion-01");
            String targetOrgUrl = SyntheticFixtureFactory.targetOrgUrl("dm-url-exclusion-01");

            DataMigrationRequest request = new DataMigrationRequest(
                    pipelineId, stepId, sourceOrgUrl, targetOrgUrl);

            mockMvc.perform(post("/datamigration")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            assertThat(event.getSafeFields()).doesNotContainKey("sourceOrgUrl");
            assertThat(event.getSafeFields()).doesNotContainKey("targetOrgUrl");
            // Org URL values must not appear in any safe field value
            String sourceOrgUrlValue = sourceOrgUrl;
            String targetOrgUrlValue = targetOrgUrl;
            event.getSafeFields().values().forEach(v -> {
                assertThat(v).doesNotContain(sourceOrgUrlValue);
                assertThat(v).doesNotContain(targetOrgUrlValue);
            });
        }

        @Test
        @DisplayName("POST /datamigration: safe log event does NOT contain raw DTO toString")
        void migrate_maskedFixture_safeLogExcludesDtoToString() throws Exception {
            String pipelineId = SyntheticFixtureFactory.pipelineId("dm-dto-exclusion-01");
            String stepId = SyntheticFixtureFactory.stepId("dm-dto-exclusion-01");

            DataMigrationRequest request = new DataMigrationRequest(
                    pipelineId, stepId,
                    SyntheticFixtureFactory.sourceOrgUrl("dm-dto-exclusion-01"),
                    SyntheticFixtureFactory.targetOrgUrl("dm-dto-exclusion-01"));

            mockMvc.perform(post("/datamigration")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            event.getSafeFields().values().forEach(v ->
                assertThat(v).doesNotContain("DataMigrationRequest"));
        }

        @Test
        @DisplayName("POST /datamigration: operation and controller are set correctly")
        void migrate_maskedFixture_safeLogMetadataCorrect() throws Exception {
            DataMigrationRequest request = new DataMigrationRequest(
                    SyntheticFixtureFactory.pipelineId("dm-meta-01"),
                    SyntheticFixtureFactory.stepId("dm-meta-01"),
                    SyntheticFixtureFactory.sourceOrgUrl("dm-meta-01"),
                    SyntheticFixtureFactory.targetOrgUrl("dm-meta-01"));

            mockMvc.perform(post("/datamigration")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            assertThat(event.getOperation()).isEqualTo("data-migration");
            assertThat(event.getController()).isEqualTo("DataMigrationController");
            assertThat(event.getOutcome()).isEqualTo(SafeLogEvent.Outcome.ACCEPTED);
        }
    }

    // ── PostRefreshTaskController ──────────────────────────────────────────────

    @Nested
    @WithMockUser
    @WebMvcTest(controllers = PostRefreshTaskController.class)
    @Import(SfdcExceptionHandler.class)
    @DisplayName("PostRefreshTaskController — masked fixture assertions (WO-124)")
    class PostRefreshMaskedFixtureTests {

        @Autowired
        private MockMvc mockMvc;

        @Autowired
        private ObjectMapper objectMapper;

        @MockBean
        private PostRefreshTaskService postRefreshTaskService;

        @MockBean
        private ClassificationPolicyResolver classificationPolicyResolver;

        @MockBean
        private SafeStructuredLogger safeStructuredLogger;

        @Test
        @DisplayName("POST /postrefresh: safe log event contains pipelineId and stepId")
        void postRefresh_maskedFixture_safeLogContainsPipelineIdAndStepId() throws Exception {
            String pipelineId = SyntheticFixtureFactory.pipelineId("pr-safe-log-01");
            String stepId = SyntheticFixtureFactory.stepId("pr-safe-log-01");

            PostRefreshRequest request = new PostRefreshRequest(pipelineId, stepId);

            mockMvc.perform(post("/postrefresh")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            assertThat(event.getSafeFields()).containsKey("pipelineId");
            assertThat(event.getSafeFields()).containsKey("stepId");
            assertThat(event.getSafeFields().get("pipelineId")).isEqualTo(pipelineId);
            assertThat(event.getSafeFields().get("stepId")).isEqualTo(stepId);
        }

        @Test
        @DisplayName("POST /postrefresh: safe log event contains no raw DTO or extra fields")
        void postRefresh_maskedFixture_safeLogContainsOnlyAllowListedFields() throws Exception {
            String pipelineId = SyntheticFixtureFactory.pipelineId("pr-allow-list-01");
            String stepId = SyntheticFixtureFactory.stepId("pr-allow-list-01");

            PostRefreshRequest request = new PostRefreshRequest(pipelineId, stepId);

            mockMvc.perform(post("/postrefresh")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            // Only pipelineId and stepId are allow-listed for this controller
            assertThat(event.getSafeFields().keySet()).containsExactlyInAnyOrder("pipelineId", "stepId");
            // No DTO class name in any field value
            event.getSafeFields().values().forEach(v ->
                assertThat(v).doesNotContain("PostRefreshRequest"));
        }

        @Test
        @DisplayName("POST /postrefresh: operation and controller metadata correct")
        void postRefresh_maskedFixture_safeLogMetadataCorrect() throws Exception {
            PostRefreshRequest request = new PostRefreshRequest(
                    SyntheticFixtureFactory.pipelineId("pr-meta-01"),
                    SyntheticFixtureFactory.stepId("pr-meta-01"));

            mockMvc.perform(post("/postrefresh")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(objectMapper.writeValueAsString(request)))
                    .andExpect(status().isOk());

            ArgumentCaptor<SafeLogEvent> captor = ArgumentCaptor.forClass(SafeLogEvent.class);
            verify(safeStructuredLogger).logEvent(captor.capture());

            SafeLogEvent event = captor.getValue();
            assertThat(event.getOperation()).isEqualTo("post-refresh");
            assertThat(event.getController()).isEqualTo("PostRefreshTaskController");
            assertThat(event.getOutcome()).isEqualTo(SafeLogEvent.Outcome.ACCEPTED);
        }
    }
}
