package com.opsera.integrator.sfdc.resources.v2.release;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Canonical v2 request DTO for release commands (deploy, validate, quick-deploy, cancel).
 *
 * <p>All fields use Jakarta Bean Validation annotations. {@code clientCorrelationId} is
 * intentionally optional so callers that omit it are not rejected; the downstream facade
 * generates a correlation identifier if one is absent.
 *
 * <p>toString() omits {@code requestedBy} and {@code clientCorrelationId} to prevent
 * user-identifying metadata from appearing in application logs.
 */
public class ReleaseCommandRequest {

    @NotNull(message = "operationType is required")
    private ReleaseOperationType operationType;

    @NotBlank(message = "customerId is required")
    private String customerId;

    @NotBlank(message = "sfdcToolId is required")
    private String sfdcToolId;

    @NotBlank(message = "taskId is required")
    @Size(max = 256, message = "taskId must not exceed 256 characters")
    private String taskId;

    /** Optional git/fallback task identifier. Mapper selects taskId over this value. */
    private String gitTaskId;

    /** Required when operationType is QUICK_DEPLOY. */
    private String deployRequestId;

    /** Optional caller identity; omitted from toString to avoid logging user data. */
    private String requestedBy;

    /** Optional caller-supplied correlation ID; generated by the facade if absent. */
    @Size(max = 64, message = "clientCorrelationId must not exceed 64 characters")
    private String clientCorrelationId;

    private String pipelineId;
    private String stepId;

    public ReleaseCommandRequest() {}

    // ---- Getters and setters ----

    public ReleaseOperationType getOperationType() { return operationType; }
    public void setOperationType(ReleaseOperationType operationType) { this.operationType = operationType; }

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public String getSfdcToolId() { return sfdcToolId; }
    public void setSfdcToolId(String sfdcToolId) { this.sfdcToolId = sfdcToolId; }

    public String getTaskId() { return taskId; }
    public void setTaskId(String taskId) { this.taskId = taskId; }

    public String getGitTaskId() { return gitTaskId; }
    public void setGitTaskId(String gitTaskId) { this.gitTaskId = gitTaskId; }

    public String getDeployRequestId() { return deployRequestId; }
    public void setDeployRequestId(String deployRequestId) { this.deployRequestId = deployRequestId; }

    public String getRequestedBy() { return requestedBy; }
    public void setRequestedBy(String requestedBy) { this.requestedBy = requestedBy; }

    public String getClientCorrelationId() { return clientCorrelationId; }
    public void setClientCorrelationId(String clientCorrelationId) { this.clientCorrelationId = clientCorrelationId; }

    public String getPipelineId() { return pipelineId; }
    public void setPipelineId(String pipelineId) { this.pipelineId = pipelineId; }

    public String getStepId() { return stepId; }
    public void setStepId(String stepId) { this.stepId = stepId; }

    /**
     * Safe toString omits requestedBy and clientCorrelationId to prevent user-identifying
     * metadata from appearing in log lines (AC-7).
     */
    @Override
    public String toString() {
        return "ReleaseCommandRequest{" +
                "operationType=" + operationType +
                ", customerId='" + customerId + '\'' +
                ", sfdcToolId='" + sfdcToolId + '\'' +
                ", taskId='" + taskId + '\'' +
                ", gitTaskId='" + gitTaskId + '\'' +
                ", deployRequestId='" + deployRequestId + '\'' +
                ", pipelineId='" + pipelineId + '\'' +
                ", stepId='" + stepId + '\'' +
                '}';
    }
}
