package com.opsera.integrator.sfdc.resources.v2.release;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Canonical v2 request DTO for release commands (deploy, validate, quick-deploy, cancel).
 *
 * <p>All fields use Jakarta Bean Validation annotations. {@code clientCorrelationId} is
 * intentionally optional so callers that omit it are not rejected; the downstream facade
 * generates a correlation identifier if one is absent.
 *
 * <p>toString() omits {@code requestedBy} and {@code clientCorrelationId} to prevent
 * user-identifying metadata from appearing in application logs.
 */
@Schema(description = "V2 release command request. Submits a typed release operation for asynchronous execution.")
public class ReleaseCommandRequest {

    @Schema(description = "Release operation to execute", requiredMode = Schema.RequiredMode.REQUIRED,
            example = "DEPLOY")
    @NotNull(message = "operationType is required")
    private ReleaseOperationType operationType;

    @Schema(description = "Opsera customer identifier", requiredMode = Schema.RequiredMode.REQUIRED,
            example = "customer-fixture-001")
    @NotBlank(message = "customerId is required")
    private String customerId;

    @Schema(description = "Salesforce tool configuration identifier", requiredMode = Schema.RequiredMode.REQUIRED,
            example = "sfdc-tool-fixture-001")
    @NotBlank(message = "sfdcToolId is required")
    private String sfdcToolId;

    @Schema(description = "Primary task identifier (step or job ID, max 256 characters)",
            requiredMode = Schema.RequiredMode.REQUIRED, example = "step-deploy-fixture-001")
    @NotBlank(message = "taskId is required")
    @Size(max = 256, message = "taskId must not exceed 256 characters")
    private String taskId;

    @Schema(description = "Optional fallback task identifier. Mapper selects taskId over this value.",
            example = "fallback-task-fixture-001")
    private String gitTaskId;

    @Schema(description = "Quick deploy request identifier. Required when operationType is QUICK_DEPLOY.",
            example = "deploy-req-fixture-001")
    private String deployRequestId;

    @Schema(description = "Optional caller identity. Omitted from logs to prevent user data exposure.",
            hidden = true)
    private String requestedBy;

    @Schema(description = "Optional caller-supplied correlation ID (max 64 characters). "
            + "Generated by the service if absent.",
            example = "corr-caller-supplied-001", maxLength = 64)
    @Size(max = 64, message = "clientCorrelationId must not exceed 64 characters")
    private String clientCorrelationId;

    @Schema(description = "Pipeline identifier for correlation and logging", example = "pipeline-fixture-001")
    private String pipelineId;

    @Schema(description = "Step identifier for correlation and logging", example = "step-deploy-fixture-001")
    private String stepId;

    public ReleaseCommandRequest() {}

    // ---- Getters and setters ----

    public ReleaseOperationType getOperationType() { return operationType; }
    public void setOperationType(ReleaseOperationType operationType) { this.operationType = operationType; }

    public String getCustomerId() { return customerId; }
    public void setCustomerId(String customerId) { this.customerId = customerId; }

    public String getSfdcToolId() { return sfdcToolId; }
    public void setSfdcToolId(String sfdcToolId) { this.sfdcToolId = sfdcToolId; }

    public String getTaskId() { return taskId; }
    public void setTaskId(String taskId) { this.taskId = taskId; }

    public String getGitTaskId() { return gitTaskId; }
    public void setGitTaskId(String gitTaskId) { this.gitTaskId = gitTaskId; }

    public String getDeployRequestId() { return deployRequestId; }
    public void setDeployRequestId(String deployRequestId) { this.deployRequestId = deployRequestId; }

    public String getRequestedBy() { return requestedBy; }
    public void setRequestedBy(String requestedBy) { this.requestedBy = requestedBy; }

    public String getClientCorrelationId() { return clientCorrelationId; }
    public void setClientCorrelationId(String clientCorrelationId) { this.clientCorrelationId = clientCorrelationId; }

    public String getPipelineId() { return pipelineId; }
    public void setPipelineId(String pipelineId) { this.pipelineId = pipelineId; }

    public String getStepId() { return stepId; }
    public void setStepId(String stepId) { this.stepId = stepId; }

    /**
     * Safe toString omits requestedBy and clientCorrelationId to prevent user-identifying
     * metadata from appearing in log lines (AC-7).
     */
    @Override
    public String toString() {
        return "ReleaseCommandRequest{" +
                "operationType=" + operationType +
                ", customerId='" + customerId + '\'' +
                ", sfdcToolId='" + sfdcToolId + '\'' +
                ", taskId='" + taskId + '\'' +
                ", gitTaskId='" + gitTaskId + '\'' +
                ", deployRequestId='" + deployRequestId + '\'' +
                ", pipelineId='" + pipelineId + '\'' +
                ", stepId='" + stepId + '\'' +
                '}';
    }
}
