-- V1__baseline.sql
-- Establishes the sfdc-integrator-service schema foundation.
-- Flyway automatically manages flyway_schema_history. This script adds a
-- service-owned metadata table so migration ordering and checksum validation
-- can be verified in CI without any business tables being required yet.
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V2__, V3__, ...).

CREATE TABLE IF NOT EXISTS sfdc_schema_info (
    id          BIGSERIAL PRIMARY KEY,
    schema_version VARCHAR(64) NOT NULL,
    applied_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sfdc_schema_info (schema_version) VALUES ('V1-baseline');
