-- V2__lifecycle_schema.sql
-- Durable lifecycle tables for release job tracking.
--
-- Design principles:
--   - Raw Salesforce payloads, credentials, tokens, and stack traces are never stored.
--   - Customer/org references use hashed identifiers for GDPR/CCPA minimization.
--   - All timestamps are stored as UTC (TIMESTAMP).
--   - Optimistic concurrency on the jobs table prevents lost updates.
--   - Checkpoint history is immutable append-only; duplicate sequence numbers are rejected.
--
-- Data classification (see governance/classification package):
--   jobs                    → CONFIDENTIAL (job metadata, correlation IDs)
--   job_checkpoints         → CONFIDENTIAL (ordered progress history)
--   worker_attempts         → CONFIDENTIAL (execution attempt metadata)
--   job_diagnostics         → CONFIDENTIAL (sanitized error summaries, never raw stacks)
--   job_retention_metadata  → INTERNAL     (retention/purge scheduling metadata)
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V3__, V4__, ...).

-- ─────────────────────────────────────────────────────────────────────────────
-- jobs
-- System of record for accepted release jobs. One row per accepted command.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS jobs (
    job_id              VARCHAR(64)     PRIMARY KEY,
    correlation_id      VARCHAR(64)     NOT NULL,
    operation_type      VARCHAR(32)     NOT NULL,
    current_state       VARCHAR(32)     NOT NULL,
    -- Hashed customer reference; callers must hash before storage (SHA-256 hex recommended).
    customer_id_hash    VARCHAR(64),
    -- Safe non-PII tool reference; opaque internal identifier.
    sfdc_tool_id        VARCHAR(64),
    pipeline_id         VARCHAR(128),
    step_id             VARCHAR(256),
    data_classification VARCHAR(32)     NOT NULL DEFAULT 'CONFIDENTIAL',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Computed retention expiry populated by a retention policy task.
    expires_at          TIMESTAMP,
    -- Optimistic concurrency version; increment on every state transition.
    version             BIGINT          NOT NULL DEFAULT 0
);

-- Status lookup: most frequent operational query path.
CREATE INDEX IF NOT EXISTS idx_jobs_current_state       ON jobs (current_state);
-- Correlation lookup: incident triage, log correlation.
CREATE INDEX IF NOT EXISTS idx_jobs_correlation_id      ON jobs (correlation_id);
-- Time-range query: active job monitoring, SLO reporting.
CREATE INDEX IF NOT EXISTS idx_jobs_created_at          ON jobs (created_at);
-- Tenant-scoped lookup: per-customer job history.
CREATE INDEX IF NOT EXISTS idx_jobs_customer_id_hash    ON jobs (customer_id_hash);


-- ─────────────────────────────────────────────────────────────────────────────
-- job_checkpoints
-- Immutable ordered progress history for a job.
-- Sequence numbers must be unique per job to prevent duplicates.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS job_checkpoints (
    id                  BIGSERIAL       PRIMARY KEY,
    job_id              VARCHAR(64)     NOT NULL REFERENCES jobs (job_id),
    sequence_number     INTEGER         NOT NULL,
    checkpoint_code     VARCHAR(64)     NOT NULL,
    state_at_checkpoint VARCHAR(32)     NOT NULL,
    -- Human-readable safe progress summary; no raw payload or credentials.
    safe_message        VARCHAR(512),
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_checkpoint_job_sequence UNIQUE (job_id, sequence_number)
);

-- Ordered history retrieval: primary query pattern for checkpoint listing.
CREATE INDEX IF NOT EXISTS idx_checkpoints_job_sequence ON job_checkpoints (job_id, sequence_number);


-- ─────────────────────────────────────────────────────────────────────────────
-- worker_attempts
-- Execution attempt history per job. Supports retry and timeout detection.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS worker_attempts (
    id              BIGSERIAL       PRIMARY KEY,
    job_id          VARCHAR(64)     NOT NULL REFERENCES jobs (job_id),
    attempt_number  INTEGER         NOT NULL,
    -- Opaque worker identity (e.g. pod name); no PII.
    worker_id       VARCHAR(128),
    started_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP,
    -- SUCCEEDED | FAILED | TIMED_OUT | null (in progress)
    outcome         VARCHAR(32),
    CONSTRAINT uq_attempt_job_number UNIQUE (job_id, attempt_number)
);

CREATE INDEX IF NOT EXISTS idx_attempts_job_id ON worker_attempts (job_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- job_diagnostics
-- Sanitized terminal diagnostic summary for a job.
-- One row per job, written when the job reaches a terminal state.
-- Stack traces, credentials, tokens, and raw CLI output are never stored here.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS job_diagnostics (
    id              BIGSERIAL       PRIMARY KEY,
    job_id          VARCHAR(64)     NOT NULL REFERENCES jobs (job_id),
    -- Sanitized human-readable summary; max 1024 chars; no PII, no stack trace.
    safe_summary    VARCHAR(1024),
    error_code      VARCHAR(64),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_diagnostics_job_id ON job_diagnostics (job_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- job_retention_metadata
-- Retention scheduling and purge eligibility tracking.
-- One row per job. Controls data lifecycle under GDPR/CCPA retention policy.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS job_retention_metadata (
    job_id              VARCHAR(64)     PRIMARY KEY REFERENCES jobs (job_id),
    -- SHORT_TERM | STANDARD | EXTENDED | AUDIT_MANDATED
    retention_hint      VARCHAR(32)     NOT NULL DEFAULT 'STANDARD',
    data_classification VARCHAR(32)     NOT NULL DEFAULT 'CONFIDENTIAL',
    -- Timestamp after which the job record is eligible for automated purge.
    purge_eligible_at   TIMESTAMP,
    -- Set when the record has been purged; used for audit trail.
    purged_at           TIMESTAMP,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
