-- V3__audit_events_schema.sql
-- Append-only audit events table for SOC 2, SOX, and GDPR compliance trail.
--
-- Design principles:
--   - Audit events are immutable once written. No UPDATE or DELETE via the application.
--   - Safe metadata (safeMetadata) contains only allow-listed keys — no raw payloads,
--     credentials, org URLs, bearer tokens, or full DTO contents.
--   - Correlation IDs link audit events to the HTTP request log for incident triage.
--   - Actor references are opaque pipeline or service identifiers — no raw user PII.
--   - Resource references use opaque job or pipeline IDs, not customer credentials.
--
-- Data classification: CONFIDENTIAL (correlation IDs, actor and resource references)
-- Retention: AUDIT_MANDATED — minimum 1 year unless a longer policy applies.
--
-- Append-only enforcement:
--   The application interface (AuditEventRepository) exposes only an append() method.
--   For PostgreSQL production environments, enforce at the database level by revoking
--   UPDATE and DELETE from the application role after applying this migration:
--
--     REVOKE UPDATE, DELETE ON audit_events FROM <app_role>;
--
--   This must be executed by a privileged DBA account as part of the initial environment
--   setup. It is NOT included in this migration script because it requires a role name
--   that is environment-specific and must not be committed as source.
--
--   Break-glass procedure (to correct or expunge an audit event in production):
--     1. Obtain an approved change ticket with legal/compliance sign-off.
--     2. Use a privileged DBA account (never the application role).
--     3. Record a post-action entry in the external SIEM before and after the change.
--     4. Re-apply the REVOKE statement to restore the restriction after the operation.
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V4__, V5__, ...).

-- ─────────────────────────────────────────────────────────────────────────────
-- audit_events
-- Immutable compliance trail for governed mutations. One row per auditable action.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_events (
    -- Globally unique event identifier (UUID v4, hex-encoded).
    event_id          VARCHAR(64)   PRIMARY KEY,
    -- Correlation identifier from the originating HTTP request (X-Correlation-Id).
    -- Links this audit event to request logs, lifecycle records, and Kafka messages.
    correlation_id    VARCHAR(64)   NOT NULL,
    -- Type of actor that initiated the action: APPLICATION, OPERATOR, or SYSTEM.
    actor_type        VARCHAR(32)   NOT NULL,
    -- Opaque actor reference: pipeline ID or service account name. No raw user PII.
    actor_ref         VARCHAR(256)  NOT NULL,
    -- Logical resource type being acted upon (matches AuditResourceType enum values).
    resource_type     VARCHAR(64)   NOT NULL,
    -- Opaque resource reference: pipeline ID, job ID, or step ID.
    resource_ref      VARCHAR(256)  NOT NULL,
    -- Governed operation name (matches AuditOperation enum values).
    operation         VARCHAR(64)   NOT NULL,
    -- Data classification tier of the audited operation (matches DataClassification enum).
    classification    VARCHAR(32)   NOT NULL DEFAULT 'CONFIDENTIAL',
    -- Safe JSON metadata: only allow-listed keys, no raw payloads or credentials.
    safe_metadata     TEXT,
    -- Timestamp when the governed action occurred (application-provided, UTC).
    event_timestamp   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Row insertion timestamp (database-provided, UTC). Not overridable by application.
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Optional: identifies the controller method that emitted this event.
    request_source    VARCHAR(256)
);

-- Correlation lookup: incident triage, cross-referencing with lifecycle and request logs.
CREATE INDEX IF NOT EXISTS idx_audit_correlation_id  ON audit_events (correlation_id);
-- Resource lookup: all audit events for a given resource type and identifier.
CREATE INDEX IF NOT EXISTS idx_audit_resource        ON audit_events (resource_type, resource_ref);
-- Actor lookup: all audit events for a given actor reference.
CREATE INDEX IF NOT EXISTS idx_audit_actor_ref       ON audit_events (actor_ref);
-- Operation lookup: all events of a given operation type across the audit history.
CREATE INDEX IF NOT EXISTS idx_audit_operation       ON audit_events (operation);
-- Time-range query: compliance window queries, retention enforcement, SLO reporting.
CREATE INDEX IF NOT EXISTS idx_audit_event_timestamp ON audit_events (event_timestamp);
