-- V4__retention_metadata_schema.sql
-- Extends job_retention_metadata with full retention lifecycle fields required
-- for GDPR/CCPA compliance: retention start, legal hold, purge eligibility status,
-- artifact reference, data category, and updated timestamp.
--
-- Design principles:
--   - legal_hold=TRUE always overrides purge_eligibility_status — automated purge
--     automation must check both columns and treat LEGAL_HOLD as blocking.
--   - purge_eligibility_status is computed by RetentionPolicyResolver and stored
--     to support indexed purge-candidate queries without runtime calculation.
--   - Timestamps are UTC throughout. The application (not the database) sets
--     retention_start and purge_eligible_at via an injectable Clock.
--   - artifact_ref is optional and used for artifact-scoped retention (e.g. generated
--     Salesforce change sets, report exports).
--
-- Indexes added:
--   - purge candidate lookup: purge_eligible_at, purge_eligibility_status
--   - legal hold filter: legal_hold
--   - artifact reference: artifact_ref
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V5__, V6__, ...).

-- ─────────────────────────────────────────────────────────────────────────────
-- Extend job_retention_metadata with retention lifecycle fields
-- ─────────────────────────────────────────────────────────────────────────────

-- Optional reference to a specific artifact (generated change set, report export).
-- NULL for job-scoped retention without a specific artifact.
ALTER TABLE job_retention_metadata ADD COLUMN IF NOT EXISTS artifact_ref VARCHAR(256);

-- Governed data category driving the retention policy (matches GovernanceDataCategory enum).
ALTER TABLE job_retention_metadata ADD COLUMN IF NOT EXISTS data_category VARCHAR(64);

-- UTC timestamp when the retention window started (set by the application at record creation).
ALTER TABLE job_retention_metadata ADD COLUMN IF NOT EXISTS retention_start TIMESTAMP;

-- Legal hold flag. When TRUE, automated purge is blocked regardless of purge_eligible_at.
ALTER TABLE job_retention_metadata ADD COLUMN IF NOT EXISTS legal_hold BOOLEAN NOT NULL DEFAULT FALSE;

-- Computed purge eligibility status: ELIGIBLE | INELIGIBLE | LEGAL_HOLD | UNKNOWN.
-- Stored to allow indexed purge-candidate queries. Updated by RetentionPolicyResolver.
ALTER TABLE job_retention_metadata ADD COLUMN IF NOT EXISTS purge_eligibility_status VARCHAR(32) NOT NULL DEFAULT 'INELIGIBLE';

-- Row modification timestamp (application-provided UTC). Updated on legal hold and status changes.
ALTER TABLE job_retention_metadata ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- ─────────────────────────────────────────────────────────────────────────────
-- Indexes for purge automation query patterns
-- ─────────────────────────────────────────────────────────────────────────────

-- Purge candidate scan: records whose retention expiration has passed.
CREATE INDEX IF NOT EXISTS idx_retention_purge_eligible_at
    ON job_retention_metadata (purge_eligible_at);

-- Status-based candidate filter: selects all ELIGIBLE records for a purge run.
CREATE INDEX IF NOT EXISTS idx_retention_purge_status
    ON job_retention_metadata (purge_eligibility_status);

-- Legal hold filter: quickly exclude all records under hold.
CREATE INDEX IF NOT EXISTS idx_retention_legal_hold
    ON job_retention_metadata (legal_hold);

-- Classification-scoped queries for compliance reporting.
CREATE INDEX IF NOT EXISTS idx_retention_classification
    ON job_retention_metadata (data_classification);

-- Artifact-scoped retention lookup.
CREATE INDEX IF NOT EXISTS idx_retention_artifact_ref
    ON job_retention_metadata (artifact_ref)
    WHERE artifact_ref IS NOT NULL;
