-- V5__audit_retention_expiry.sql
-- Adds retention_expiry_at column to audit_events for GDPR/CCPA retention enforcement.
--
-- Audit records for lifecycle mutations must be retained for at least one year unless a
-- stricter configured policy applies (see AuditEventWriter for calculation logic).
-- A NULL value means the row predates this migration and retains the default 1-year policy.
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V6__, ...).

ALTER TABLE audit_events
    ADD COLUMN IF NOT EXISTS retention_expiry_at TIMESTAMP;

-- Index for retention enforcement queries and purge eligibility scans.
CREATE INDEX IF NOT EXISTS idx_audit_retention_expiry ON audit_events (retention_expiry_at);
