-- V6__retention_purge_schema.sql
-- Adds purge run tracking and performance indexes for the automated retention purge process.
--
-- Design principles:
--   - purge_runs table provides operational recovery data beyond per-event audit trail.
--     Callers can query a single row to determine whether a previous run completed
--     before starting a new one (supplementary to the audit_events table).
--   - purged_at column already exists in job_retention_metadata (V2 migration).
--     This migration adds an index on it for efficient "not yet purged" candidate selection.
--   - Purge run records are append-only from the application layer; no DELETE grant needed.
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V7__, ...).

-- ─────────────────────────────────────────────────────────────────────────────
-- purge_runs
-- Operational tracking table for retention purge runs.
-- One row per purge run; supports recovery query and duplicate run detection.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purge_runs (
    run_id          VARCHAR(64)     PRIMARY KEY,
    mode            VARCHAR(16)     NOT NULL,           -- DISABLED | DRY_RUN | ENFORCE
    started_at      TIMESTAMP       NOT NULL,
    completed_at    TIMESTAMP,
    selected_count  INTEGER         NOT NULL DEFAULT 0,
    purged_count    INTEGER         NOT NULL DEFAULT 0,
    skipped_count   INTEGER         NOT NULL DEFAULT 0,
    failed_count    INTEGER         NOT NULL DEFAULT 0,
    duration_ms     BIGINT          NOT NULL DEFAULT 0,
    -- COMPLETED | COMPLETED_WITH_FAILURES | ABORTED | DRY_RUN_COMPLETE
    outcome         VARCHAR(32),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Time-range query: most recent purge runs for operational review.
CREATE INDEX IF NOT EXISTS idx_purge_runs_started_at
    ON purge_runs (started_at DESC);

-- Outcome filter: find failed or aborted runs for incident response.
CREATE INDEX IF NOT EXISTS idx_purge_runs_outcome
    ON purge_runs (outcome);


-- ─────────────────────────────────────────────────────────────────────────────
-- Index on job_retention_metadata.purged_at for candidate selection
-- ─────────────────────────────────────────────────────────────────────────────

-- Efficiently filter already-purged records (purged_at IS NULL) from candidate selection.
CREATE INDEX IF NOT EXISTS idx_retention_purged_at
    ON job_retention_metadata (purged_at)
    WHERE purged_at IS NULL;
