-- V7__rollback_decision_fields.sql
-- Extends the jobs table with rollback decision support fields.
--
-- Design principles:
--   - All fields are advisory only; no automated rollback is triggered.
--   - diagnosticSummary is capped at 512 characters; raw logs, stack traces,
--     credentials, tokens, and Salesforce payloads are never stored here.
--   - rollback_reason_code and failed_stage store enum name strings for
--     readability in operational queries.
--   - rollback_updated_at records when rollback decision fields were last evaluated.
--
-- Data classification: CONFIDENTIAL (same as jobs table).
--
-- IMMUTABLE: Do not edit this file after it has been applied to any environment.
-- Fixes require a new versioned migration script (V8__, ...).

ALTER TABLE jobs
    ADD COLUMN IF NOT EXISTS rollback_eligible           BOOLEAN,
    ADD COLUMN IF NOT EXISTS rollback_recommended        BOOLEAN,
    ADD COLUMN IF NOT EXISTS rollback_reason_code        VARCHAR(64),
    ADD COLUMN IF NOT EXISTS failed_stage                VARCHAR(32),
    ADD COLUMN IF NOT EXISTS last_successful_checkpoint  VARCHAR(128),
    ADD COLUMN IF NOT EXISTS rollback_diagnostic_summary VARCHAR(512),
    ADD COLUMN IF NOT EXISTS rollback_updated_at         TIMESTAMP;

-- Index for fast lookup of rollback-eligible failed jobs (operational query path).
CREATE INDEX IF NOT EXISTS idx_jobs_rollback_eligible
    ON jobs (rollback_eligible)
    WHERE rollback_eligible = TRUE;
